apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-manual-testing-vllm-default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/chatbot-manual-testing-vllm-default:ebfd3e9090d0fee20761ea36f4b490bd08de279f@sha256:10e931aca3a23afbb3a9206a881e0a3914f5667df70a5154c3977ac797aff03e # use pre-built to bootstrap 
          name: app-inference
